name: Build Native Image

on:
  push:
    branches:
      - main  # 在推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GraalVM 17
      uses: graalvm/setup-graalvm@v1
      with:
        version: '17.0.8'  # 具体的 GraalVM 版本
        java-package: jdk
        components: native-image

    - name: Set up environment variables
      run: echo JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java)))) >> $GITHUB_ENV

    - name: Build with native-image
      run: |
        ./gradlew build nativeImage  # 如果你使用 Gradle
        # 或者 ./mvnw package -Pnative  # 如果你使用 Maven

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: native-application
        path: build/native-image/* # or target/native-image/* if using Maven

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automated release from GitHub Actions
        draft: false
        prerelease: false
        generate_release_notes: false
        files: |
          build/native-image/*  # 或者 target/native-image/* 如果使用 Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
